name: hydhome
description: hydhome

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #权限管理
#  permission_handler: '^4.0.0'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2
  dio: ^3.0.8 #latest version
  fluttertoast: ^3.1.3
  fluro: ^1.5.1
  get_it: ^3.1.0
  shared_preferences: ^0.5.6
  #UI
  pull_to_refresh: ^1.5.7
  #轮播
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0
  # State
  provider: ^4.0.1
  rxdart: ^0.23.1
  #  flutter_screenutil: ^0.4.2

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.18+1
#  flutter_webview_plugin: ^0.3.8

  device_info: ^0.4.1+4
  package_info: ^0.4.0+13
  quiver: ^2.0.5

  # 本地json对象存储
  localstorage: ^3.0.1+4

  # Html Encoder/Decoder
#  html_unescape: ^1.0.1+3
  # 解析html标签
  flutter_html: ^0.11.1

  # 判断list是否相等
  collection: ^1.14.11
#  #闲鱼框架
#  fish_redux: ^0.3.1

  # third_app
#  url_launcher: ^5.1.6 #启动第三方app
#  share: 0.6.2+1 #分享
#  launch_review: ^2.0.0
#  open_file: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


  assets:
    - assets/images/
