name: base
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0

  dio: ^4.0.0-beta7
  bot_toast: ^4.0.0+1
  shared_preferences: ^2.0.3
  #路由
  fluro: ^2.0.3
      #  thrio: ^1.7.6

      #    微信支付以及登录
  fluwx: ^3.3.2
      #UI
  pull_to_refresh: ^1.6.4
      #  lazy_load_refresh_indicator:
      #  tab_indicator_styler: ^1.0.0
#  getwidget: ^2.0.0-nullsafety.3
      #  柱状图
#  charts_flutter: ^0.10.0
      #  动画
  animate_do: ^2.0.0

      #生命周期监听
  lifecycle: ^0.1.1+1
      #轮播
      #  flutter_swiper:
      #图片缓存
  cached_network_image: ^3.0.0-nullsafety
      #  paulonia_cache_image:

      #插件
  device_info: ^2.0.0
  package_info: ^2.0.0
  open_settings: ^1.0.3
      #  权限
  permission_handler: ^6.0.1

      #适配
      #  flutter_screenutil: ^4.0.3+3
  flutter_screenutil: ^5.0.0-nullsafety.7
  mime_type: ^0.3.2

      #  flutter_common_utils: ^1.1.0

      #  图片选择器
  file_picker: ^3.0.1
  image_picker: ^0.7.4
  image_picker_for_web: ^2.0.0

  url_launcher: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
